### ISSUE TITLE
Welcome page / greeting

### ISSUE THREAD

**Issue by TomasS666** [Ramon96/aria-1920#15]
**Is your feature request related to a problem? Please describe.**
We should think about what the user wants to see at the welcome page. What does Spotify do? Is that what we want? Is that what Joost wants?

**Describe the solution you'd like**
It's of course a project that resolves around Spotify. The focus lies in enhancing Spotify, not creating a new Spotify. But it's worth discussing what Joost would like to see at the starting screen.

**Describe alternatives you've considered**
Alternative could be anything we or Joost would think can enhance the overall experience. But this is not the main focus yet, but it should be in there.

**Comment by Ramon96** [comment]
Joost told us on Friday we should redirect the user to the search page. Maybe making it more exciting there.
