### ISSUE TITLE
[Slider] The slider doesnt seem to be the same on android

### ISSUE THREAD

**Issue by Ramon96** [Ramon96/aria-1920#39]
Title.
Android transforms not the same as desktop and ios

**Comment by TomasS666** [comment]
*remote debugging tomorrow for max half an hour. 

If we can't figure it out, we need to find a quick soltution

**Comment by TomasS666** [comment]
Fixed. Android class was overwriting transform. 

Tested on Huawei P20 Mate lite in a Chrome Browser.
