### ISSUE TITLE
Externe platform configureren

### ISSUE THREAD

**Issue by Ramon96** [Ramon96/aria-1920#6]
De gebruiker moet in staat zijn om externe platformen zoals bijvoorbeeld twitter aan te kunnen melden (of juist afmelden als de gebruiker dat wilt)

**Comment by TomasS666** [comment]
Note to us:
Liefst dit even samen fixen de eerste helft van de volgende week. Dan hebben we speling voor het finetunen en andere extra dingen.

**Comment by Ramon96** [comment]
Dit kan geclosed worden. Inloggen bij externe partijen is niet nodig om data op te kunnen halen.
