### ISSUE TITLE
Woordweb maken op basis van persoonlijke keywords

### ISSUE THREAD

**Issue by Ramon96** [Ramon96/aria-1920#7]
De gebruiker krijgt bij de settings pagina een data vis te zien op basis van keywords die hij zelf kan invullen

**Comment by TomasS666** [comment]
Dit gaan we uitstellen totdat Joost het wel graag zou willen zien. Of als wij daar tijd voor over houden.

**Comment by Ramon96** [comment]
Dit past niet meer binnen de deadline van de laatste sprint. Kan heropend worden als we verder gaan met joost
